---
- name: Install required packages
  apt:
    name:
      - python3-psycopg2
      - postgresql-16-pgvector
    state: present
    update_cache: yes
  tags:
    - extensions
    - pgvector

- name: Reload PostgreSQL to load new extension
  service:
    name: postgresql
    state: reloaded
  tags:
    - extensions
    - pgvector

- name: Wait for PostgreSQL to be ready
  wait_for:
    port: 5432
    delay: 3
  tags:
    - extensions
    - pgvector

- name: Enable pgvector extension
  community.postgresql.postgresql_ext:
    db: "{{ db_name }}"
    name: pgvector
    state: present
    login_host: "{{ db_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_pass }}"
    login_port: "{{ db_port }}"
  tags:
    - extensions
    - pgvector
