---
- name: Congfigure Postgresql
  template:
    src: ubuntu_postgresql.j2
    dest: /etc/postgresql/{{ version }}/main/postgresql.conf

- name: Restart postgresql
  service:
    name: postgresql
    state: restarted