---
- name: Configure postgres port.
  lineinfile:
    dest: "/etc/postgresql/{{ version }}/main/postgresql.conf"
    regexp: "^#?port.+$"
    line: "port = '{{ postgres_port }}'"
    state: present
    mode: 0644

- name: Add new configuration to "postgresql.conf"
  blockinfile:
    dest: /etc/postgresql/{{ version }}/main/postgresql.conf
    block: |
      include 'server.conf'

- name: Add new configuration to "server.conf"
  blockinfile:
    create: yes
    owner: postgres
    group: postgres
    dest: /etc/postgresql/{{ version }}/main/server.conf
    block: |
      listen_addresses = '{{ postgres_listen_addresses }}'

- name: Restart postgresql
  service:
    name: postgresql
    state: restarted
