---
- name: Install ETCD
  ansible.builtin.apt:
    name: etcd
    state: present
    update_cache: true

- name: Remove old ETCD data
  ansible.builtin.file:
    path: "{{ percona_postgresql_etcd_data_dir }}"
    state: absent
   when: percona_postgresql_etcd_reinitialize | bool
 
- name: Configure ETCD
  ansible.builtin.template:
    src: etcd.conf.yaml.j2
    dest: "{{ percona_postgresql_etcd_config_path }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart etcd

- name: Enable ETCD service
  ansible.builtin.service:
    name: etcd
    enabled: true
