---
- name: Show postgres group
  debug:
    msg: "{{ groups['postgres'] }}"

- name: Show backend hosts
  debug:
    msg: "{{ item }} -> {{ hostvars[item].ansible_host }}"
  loop: "{{ groups['postgres'] }}"
  
- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true
    
- name: Ensure HAProxy group exists
  ansible.builtin.group:
    name: "{{ percona_postgresql_haproxy_group }}"
    system: true
    state: present

- name: Ensure HAProxy user exists
  ansible.builtin.user:
    name: "{{ percona_postgresql_haproxy_user }}"
    group: "{{ percona_postgresql_haproxy_group }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    state: present

- name: Configure HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ percona_postgresql_haproxy_config_path }}"
    owner: root
    group: "{{ percona_postgresql_haproxy_group }}"
    mode: "0640"
    validate: "haproxy -f %s -c"
  notify:
    - Restart haproxy

- name: Enable and start HAProxy
  ansible.builtin.service:
    name: haproxy
    enabled: true
    state: started
