---
##################
# Postgres Installation #
##################
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Installation of Postgres
  include_tasks: "{{ ansible_distribution }}.yml"

#########################
# Postgres Configuration #
#########################
- name: Configuration on Postgres
  include_tasks: "configure.yml"