---
- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Install Percona PostgreSQL packages
  ansible.builtin.include_tasks: ubuntu.yml
  when:
    - "'postgres' in groups"
    - inventory_hostname in groups['postgres']

- name: Configure ETCD
  ansible.builtin.include_tasks: etcd.yml
  when:
    - "'etcd' in groups"
    - inventory_hostname == groups['etcd']

- name: Configure Patroni
  ansible.builtin.include_tasks: patroni.yml
  when:
    - "'postgres' in groups"
    - inventory_hostname in groups['postgres']

- name: Configure HAProxy
  ansible.builtin.include_tasks: haproxy.yml
  when:
    - "'haproxy' in groups"
    - inventory_hostname in groups['haproxy']

- name: Configure WAL-G DR
  ansible.builtin.import_tasks: wal_g.yml
  when:
    - percona_postgresql_enable_dr
    - "'postgres' in groups"
    - inventory_hostname in groups['postgres']