---
##################
# Percona_cluster #
##################
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Installation of Galera Cluster on Ubuntu
  include_tasks: Debian.yml
  when: ansible_os_family == "Debian"