---
- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Install Percona PostgreSQL packages
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  when:
    - "'postgres' in groups"
    - inventory_hostname in groups['postgres']

- name: Configure ETCD
  ansible.builtin.include_tasks: etcd.yml
  when:
    - "'etcd' in groups"
    - inventory_hostname == groups['etcd']

- name: Configure Patroni
  ansible.builtin.include_tasks: patroni.yml
  when:
    - "'postgres' in groups"
    - inventory_hostname in groups['postgres']

- name: Configure HAProxy
  ansible.builtin.include_tasks: haproxy.yml
  when:
    - "'haproxy' in groups"
    - inventory_hostname in groups['haproxy']
