---
- name: Create postgres_exporter directory
  ansible.builtin.file:
    path: /etc/postgres_exporter
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure postgres_exporter environment
  ansible.builtin.template:
    src: postgres_exporter.env.j2
    dest: /etc/postgres_exporter/postgres_exporter.env
    owner: root
    group: root
    mode: "0600"
  notify: Restart postgres_exporter

- name: Enable postgres_exporter service
  ansible.builtin.systemd:
    name: postgres_exporter
    enabled: true
    state: started
