---
- name: Create postgres_exporter directory
  ansible.builtin.file:
    path: /etc/postgres_exporter
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure postgres_exporter environment
  ansible.builtin.template:
    src: postgres_exporter.env.j2
    dest: /etc/postgres_exporter/postgres_exporter.env
    owner: root
    group: root
    mode: "0600"
  notify: restart postgres_exporter

- name: Create exporter role
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ percona_postgresql_exporter_user }}"
    password: "{{ percona_postgresql_exporter_password }}"
    role_attr_flags: LOGIN
    state: present

- name: Grant pg_monitor role
  become_user: postgres
  community.postgresql.postgresql_membership:
    group: pg_monitor
    target_roles:
      - "{{ percona_postgresql_exporter_user }}"
    state: present

- name: Enable postgres_exporter service
  ansible.builtin.systemd:
    name: postgres_exporter
    enabled: true
    state: started
