---
- name: Create users in Postgres
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    encrypted: true
  with_items:
    - "{{ psql_users }}"
  tags:
    - create_user
  when:
    - inventory_hostname not in groups['slave']
