---
- name: Create users in Postgres
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    port: "{{ postgres_port }}"
  with_items:
    - "{{ psql_users }}"
  no_log: true
  tags:
    - create_user
  when:
    - inventory_hostname not in groups['slave']

- name: Ensure users in Postgres are configured
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    db: "{{ item.db | default(omit) }}"
    port: "{{ postgres_port }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ psql_users }}"
  no_log: true
  tags:
    - create_user
  when:
    - inventory_hostname not in groups['slave']
