---
- name: restart etcd
  ansible.builtin.service:
    name: etcd
    state: restarted

- name: restart patroni
  ansible.builtin.service:
    name: patroni
    state: restarted
    enabled: true

- name: restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true