---
- name: Restart etcd
  ansible.builtin.service:
    name: etcd
    state: restarted

- name: Restart patroni
  ansible.builtin.service:
    name: patroni
    state: restarted

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: Restart postgres_exporter
  ansible.builtin.systemd:
    name: postgres_exporter
    state: restarted
