---
version: 16

postgres_port: 5432

cluster_name: postgres-cluster

postgres_listen_addresses: "0.0.0.0"

patroni_rest_port: 8008

replication: true

replica_user: replicator
replica_pass: Replicator@123

etcd_hosts:
  - 192.168.8.19:2379
  - 192.168.8.20:2379

haproxy_port: 5432

database_creation: true

users_creation: true

psql_databases:
  - name: appdb

psql_users:
  - name: appuser
    password: AppUser@123
    db: appdb