---
- name: Gather OS specific variables
  include_vars:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      paths:
        - vars

- name: Install PostgreSQL Packages
  include_tasks: postgres.yml
  when: inventory_hostname in groups['postgres']

- name: Configure etcd
  include_tasks: etcd.yml
  when: inventory_hostname in groups['etcd']

- name: Configure Patroni
  include_tasks: patroni.yml
  when: inventory_hostname in groups['postgres']

- name: Configure HAProxy
  include_tasks: haproxy.yml
  when: inventory_hostname in groups['haproxy']